package kasım13;

public class Yapılacaklar {

    /*
    1-SQL TEKRARI BUGÜNÜN FULL UYGLAMASINI YAP
    2-HACKER RANK'İ İNCELE
    3-YARININ PLANLAMASINI YAP
    PROJELER OLSUN Bİ TANE EKSİK İLK 10 DKSI FALAN OLAN BİR DERS VARDI MAP05 OLMASI LAZIM ONA BAK
    SONRA MİNİ PROJENİN 2. DERSİNİ İNCELE
    SONRA KALAN PROJELERE BAK
    BİR DE SLACK ÇALIŞMA GRUBUNDAKİ TARAMAYI YAP ORDAKİ DÖKÜMANLARI LOCALE AL
    SQL KESİNLİKLE ÖNCELİK OLMALI  DÜNÜ İYİ TEKRAR ET BU OKEY
     */






}
